package com.foreach.synchronizer.text.io;

import com.foreach.spring.localization.LanguageConfigurator;
import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayOutputStream;

import static org.junit.Assert.assertEquals;

public class TestXmlLocalizedTextWriter extends BaseLocalizedTextWriterTest {

    private String expectedOutput = "<list>\n" +
            "  <text>\n" +
            "    <application>myApp</application>\n" +
            "    <group>myGroup</group>\n" +
            "    <label>my.label</label>\n" +
            "    <used>false</used>\n" +
            "    <autoGenerated>false</autoGenerated>\n" +
            "    <created>2012-01-31 23:00:00.0 UTC</created>\n" +
            "    <fields>\n" +
            "      <language>en</language>\n" +
            "      <text>This is a test!</text>\n" +
            "    </fields>\n" +
            "    <fields>\n" +
            "      <language>nl</language>\n" +
            "      <text>Dit is een test!</text>\n" +
            "    </fields>\n" +
            "  </text>\n" +
            "</list>";

    @Before
    public void setup() {
        new LanguageConfigurator( TestLanguage.class );
    }

    @Test
    public void testWrite() throws Exception {

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        XmlLocalizedTextWriter xmlLocalizedTextWriter = new XmlLocalizedTextWriter( outputStream );

        xmlLocalizedTextWriter.write( createLocalizedTexts() );

        String actualOutput = new String( outputStream.toByteArray() );

        assertEquals( expectedOutput, actualOutput );
    }

}
